my progress to ticket 8
Zipeth1010/mark-nc-games pull request #4
Opened 2023-04-18 14:54 UTC by Zipeth1010

2023-04-18 15:14 UTC, RichardNeat requested changes
Nice one Mark - just a few tweaks please as I've outlined in the comments below. Drop me a message when it's done I'll take another look.

I would also suggest taking a look at your styling as now would be a good time. Lets focus on that mobile first approach to styling, some of your UI looks a little smushed in that mobile view.

We may also want to consider some error handling, as you are allowing the user to enter a username it's possible that could go wrong. Or we can hardcode a user in for now until we have login functionality later. But some error handling still wouldn't hurt.

Lastly, when posting the comment ideally that new comment should appear at the top i.e. most recent first. This might be an issue with the back end so don't worry too much if you don't think it's a quick fix.

2023-04-18 15:14 UTC, RichardNeat commented on src/Components/CommentList.jsx
> +  const commentToSubmit = {
This is technically not wrong, but it's good to keep control of when things are happening and to make it clear why the code has been written.. We only need this object to be constructed when we are submitting the form so it would make sense to bring this down to line 28.5, this keeps our code tidy and it's a bit clearer why you are doing this.

2023-04-18 15:14 UTC, RichardNeat commented on src/Components/CommentList.jsx
> +      <section type="CommentForm">
Nice one good use of controlled forms here. You could make use of this control you have to set the input body to empty after the post has been submitted for a good user experience.

2023-04-18 15:14 UTC, RichardNeat commented on src/Components/CommentList.jsx
> +          <input
It would be more appropriate to use a textArea html tag here so the user can see the entire comment

2023-04-19 09:48 UTC, Keb84 approved these changes
Changes are good Mark. Ready to merge 🙂

2023-04-19 09:49 UTC, merged